CREATE DATABASE ecommerce;
USE ecommerce;

-- Create Tables
CREATE TABLE customers (
    customer_id VARCHAR(50),
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(10)
);

CREATE TABLE orders (
    order_id VARCHAR(50),
    customer_id VARCHAR(50),
    order_status VARCHAR(50),
    order_purchase_timestamp DATETIME,
    order_approved_at DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATETIME
);

CREATE TABLE products (
    product_id VARCHAR(50),
    product_category_name VARCHAR(100),
    product_name_lenght FLOAT,
    product_description_lenght FLOAT,
    product_photos_qty FLOAT,
    product_weight_g FLOAT,
    product_length_cm FLOAT,
    product_height_cm FLOAT,
    product_width_cm FLOAT
);

CREATE TABLE sellers (
    seller_id VARCHAR(50),
    seller_zip_code_prefix INT,
    seller_city VARCHAR(100),
    seller_state VARCHAR(10)
);

CREATE TABLE order_items (
    order_id VARCHAR(50),
    order_item_id INT,
    product_id VARCHAR(50),
    seller_id VARCHAR(50),
    shipping_limit_date DATETIME,
    price FLOAT,
    freight_value FLOAT
);

CREATE TABLE payments (
    order_id VARCHAR(50),
    payment_sequential INT,
    payment_type VARCHAR(50),
    payment_installments INT,
    payment_value FLOAT
);


-- Analytics part

SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM order_items;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM payments;


-- BASIC QUERIES

-- 1. ALL Unique cities where customers are located
SELECT DISTINCT customer_city
FROM customers;

-- 2. Number of orders placed in 2017
SELECT COUNT(*) AS total_orders_2017
FROM orders
WHERE STR_TO_DATE(
    order_purchase_timestamp,
    '%m/%d/%Y %H:%i'
) >= '2017-01-01'
AND STR_TO_DATE(
    order_purchase_timestamp,
    '%m/%d/%Y %H:%i'
) < '2018-01-01';

-- 3. Total sales per category
SELECT 
    p.product_category,
    ROUND(SUM(oi.price),2) AS total_sales
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY total_sales DESC
LIMIT 10;

-- 4. Percentage of orders paid in installments
SELECT 
ROUND(
	COUNT(DISTINCT CASE WHEN payment_installments > 1 THEN order_id END) * 100.0
	/ COUNT(DISTINCT order_id), 2
) AS installment_percentage
FROM payments;

-- 5. Number of customers from each state.
SELECT 
customer_state,
COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;


-- Intermediate Queries

-- 1. Number of orders per month in 2018.
SELECT DATE_FORMAT(STR_TO_DATE(order_purchase_timestamp, '%m/%d/%Y %H:%i'),'%Y-%m') AS month,
	COUNT(order_id) AS total_orders
	FROM orders
	WHERE STR_TO_DATE(order_purchase_timestamp,'%m/%d/%Y %H:%i') >= '2018-01-01'
	AND STR_TO_DATE(order_purchase_timestamp,'%m/%d/%Y %H:%i') < '2019-01-01'
GROUP BY month
ORDER BY month;

-- 2. Average number of products per order, grouped by customer city.
SELECT c.customer_city,
ROUND(AVG(t.product_count),2) AS avg_products_per_order
FROM (
    SELECT order_id,
    COUNT(*) AS product_count
    FROM order_items
    GROUP BY order_id
) t
JOIN orders o
ON t.order_id = o.order_id
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC;

-- 3. Percentage of total revenue contributed by each product category.
SELECT 
    p.product_category,
	SUM(oi.price) AS category_revenue,
	ROUND(SUM(oi.price) * 100.0 /(SELECT SUM(price)FROM order_items), 2) AS revenue_percentage
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY category_revenue DESC;

-- 4. Correlation between product price and the number of times a product has been purchased.
SELECT (COUNT(*) * SUM(avg_price * purchase_count) - SUM(avg_price) * SUM(purchase_count))
/ SQRT((COUNT(*) * SUM(avg_price * avg_price) - POWER(SUM(avg_price), 2))
*(COUNT(*) * SUM(purchase_count * purchase_count) - POWER(SUM(purchase_count), 2))) AS correlation
FROM (SELECT product_id, COUNT(*) AS purchase_count, AVG(price) AS avg_price FROM order_items
GROUP BY product_id) t;

-- 5. Total revenue generated by each seller, and rank them by revenue.
SELECT
    oi.seller_id,
    SUM(oi.price) AS revenue,
    RANK() OVER (ORDER BY SUM(oi.price) DESC) AS rnk
FROM order_items oi
GROUP BY oi.seller_id;


-- Advanced Queries

-- 1. Moving average of order values for each customer over their order history.
WITH order_value AS (SELECT o.customer_id, o.order_id, o.order_purchase_timestamp,
        SUM(oi.price) AS order_value
    FROM orders o JOIN order_items oi ON o.order_id = oi.order_id
    GROUP BY o.customer_id, o.order_id, o.order_purchase_timestamp)
SELECT customer_id, order_id, order_purchase_timestamp, order_value,
    AVG(order_value) OVER(PARTITION BY customer_id ORDER BY order_purchase_timestamp 
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg
    FROM order_value;
  
-- 2. Cumulative sales per month for each year.
SELECT
 year,
    month,
    month_name,
    monthly_sales,
    ROUND(SUM(monthly_sales) OVER (PARTITION BY year ORDER BY month), 2) AS cumulative_sales
FROM (SELECT
        YEAR(STR_TO_DATE(o.order_purchase_timestamp, '%m/%d/%Y %H:%i')) AS year,
        MONTH(STR_TO_DATE(o.order_purchase_timestamp, '%m/%d/%Y %H:%i')) AS month,
        MONTHNAME(STR_TO_DATE(o.order_purchase_timestamp, '%m/%d/%Y %H:%i')) AS month_name,
        ROUND(SUM(oi.price),2) AS monthly_sales
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY year, month, month_name) x
ORDER BY year, month;

-- 3. Year-Over-Year growth rate of total sales.
SELECT year,total_sales,
    LAG(total_sales) OVER(ORDER BY year) AS previous_year_sales,
    ROUND((total_sales - LAG(total_sales) OVER(ORDER BY year))
        / LAG(total_sales) OVER(ORDER BY year) * 100, 2) AS yoy_growth_percentage
FROM(SELECT
        YEAR(STR_TO_DATE(o.order_purchase_timestamp,'%m/%d/%Y %H:%i')) AS year,
        SUM(oi.price) AS total_sales
    FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY YEAR(STR_TO_DATE(o.order_purchase_timestamp, '%m/%d/%Y %H:%i'))) x
ORDER BY year;

-- 4. Retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.
SELECT 
ROUND(COUNT(DISTINCT r.customer_id)*100.0/
COUNT(DISTINCT o.customer_id), 2) AS retention_rate
FROM orders o
LEFT JOIN orders r
ON o.customer_id=r.customer_id
AND r.order_purchase_timestamp >
o.order_purchase_timestamp
AND r.order_purchase_timestamp <=
DATE_ADD(o.order_purchase_timestamp,INTERVAL 6 MONTH);

-- 5. Top 3 customers who spent the most money in each year.
SELECT * FROM(
SELECT
YEAR(STR_TO_DATE(order_purchase_timestamp,'%m/%d/%Y %H:%i')) year,
customer_id,
SUM(price) total_spent,
RANK() OVER(
PARTITION BY YEAR(STR_TO_DATE(order_purchase_timestamp,'%m/%d/%Y %H:%i'))
ORDER BY SUM(price) DESC) rnk
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY year,customer_id)x
WHERE rnk<=3;
